### ISSUE TITLE
0.16 support

### ISSUE THREAD

**Issue by minecrafter** [voxelwind/voxelwind#16]
We need to prepare for 0.16 support. A new branch has been created that contains partial 0.16 support, but more information about the protocol needs to be deciphered.

**Comment by minecrafter** [comment]
**Current status**:

Partial 0.16 support. I am currently having to rely on external testers as I do not have an Android device at the moment.

Almost every packet has changed (data formats and packet IDs), including the `McpeLogin` packet. Data format changes will require some work to figure out, but it is known that most integers have been replaced with VarInts similar to the PC version.

**Comment by TheDiamondYT1** [comment]
Try using the Bluestacks emulator @minecrafter. And no, not Bluestacks 2 - the original one.

Bluestacks 2 is good and runs well on my bad 3GB RAM Windows 10 All in one PC, but ive heard you dont like the new Bluestacks.

**Comment by TheDiamondYT1** [comment]
Currently i am booting up Bluestacks 2 and going to install the 0.16 update because it crashes on my tablet.

**Comment by minecrafter** [comment]
I've never used Bluestacks before - I'm just not in favor of emulating an ARM device on an already weak computer.

**Comment by TheDiamondYT1** [comment]
It turns out for me 0.15+ crashes on bluestacks.

**Comment by dktapps** [comment]
BlueStacks sucks hard. I get all kinds of graphical issues. Nox is a MUCH better alternative, but Play is broken in the current build, so you'd need an x86 APK. http://en.bignox.com

**Comment by stayandwait** [comment]
@minecrafter Just a heads up auto jump doesn't seam to be functioning.

**Comment by minecrafter** [comment]
@stayandwait it's not implemented.

**Comment by minecrafter** [comment]
MiNET has a better implementation of 0.16, so I'll probably use their documentation.

**Comment by minecrafter** [comment]
It's done. :+1:
