### ISSUE TITLE
Migrate to entity component system

### ISSUE THREAD

**Issue by minecrafter** [voxelwind/voxelwind#45]
Mojang has explained that the entity system in MCPE will be based on an entity component system. Voxelwind currently uses an inheritance-based system. However, since very little logic has been implemented in that system (aside from motion and players), we can move over to an ECS easily.

**Comment by minecrafter** [comment]
Initial API design:

* `Entity.provides(Class<? extends Component>)`
* `Entity.get(Class<? extends Component>)`
* `Entity.set(Class<? extends Component>)`
* `Entity.getSystems()`
* `Entity.addSystem()`
* `Entity.removeSystem()`

Individual `Component`s would most likely be immutable (hence the need for an `Entity.set()` method).

@MiniDigger It's something to consider. Remember, you can contribute the code to add this to Voxelwind.

**Comment by minecrafter** [comment]
I've started on this myself.

**Comment by TheDiamondYT1** [comment]
This is done isint it?

**Comment by minecrafter** [comment]
Largely.
