### ISSUE TITLE
Breaking the grass doesn't give drops

### ISSUE THREAD

**Issue by stayandwait** [voxelwind/voxelwind#47]
When you break the grass no item blocks drop anymore.

![2016-10-31_1829](https://cloud.githubusercontent.com/assets/15825041/19873941/2a19916a-9f98-11e6-9110-f38b8905564f.png)

**Comment by minecrafter** [comment]
This seems to be mostly incorrect decoding of `McpeRemoveBlock`.

**Comment by minecrafter** [comment]
I've fixed this issue. However, since I'm refactoring Voxelwind's entity handling, all current work is being done in a separate branch.
