### ISSUE TITLE
Scrolling with your mouse doesn't select all items

### ISSUE THREAD

**Issue by stayandwait** [voxelwind/voxelwind#48]
When you scroll with your mouse to pick an item from the hot bar, your mouse will get stuck and only go to the second hotbar slot. I'm trying to select stone from my hotbar, but scrolling to select the item doesn't work. Also pressing numbers 1-8 on your keyboard moves your hotbar selection back to slot 1 in your hotbar.  Affects iOS and Android too when taping to switch between hotbar slots.

![2016-10-31_1840](https://cloud.githubusercontent.com/assets/15825041/19874174/ae371f16-9f99-11e6-9849-81df989a99c7.png)

**Comment by minecrafter** [comment]
I'm currently only testing on mobile (iOS and Android). Windows 10 Edition is another can of worms I do not wish to handle at the moment.

**Comment by stayandwait** [comment]
@minecrafter This is happening for iOS and Android too, not just Windows 10 Edition.

**Comment by minecrafter** [comment]
Regardless, this is a low priority.

**Comment by stayandwait** [comment]
Thank you
