### ISSUE TITLE
Exchange friendship links? 

### ISSUE THREAD

**Issue by DefinitlyEvil** [voxelwind/voxelwind#49]
Hi, 
First of all this is an awesome project of course and I can't wait testing it out. :D 
I will do some tests to see if there is any problems with DragonProxy and then I will put it into our support list. ;) 
Btw, if possible, we'd like to create a demo server to demonstrate both DragonProxy's and VoxelWind's performance. :D 

Love (jk xD), 
The Ultimate Awesome and Handsome Evil Dude

**Comment by TheDiamondYT1** [comment]
Theres a gitter room aswell def

**Comment by minecrafter** [comment]
At the moment, Voxelwind is more of a demo than a fully-fledged server.

You are free to create your own test server with Voxelwind - nothing is stopping you with the exception of Voxelwind being incomplete.

**Comment by DefinitlyEvil** [comment]
okay xD
