### ISSUE TITLE
Says my protocol is 0 when its really 201

### ISSUE THREAD

**Issue by lukeeey** [voxelwind/voxelwind#56]
i know this is dead, but ive been editing it and i connected and it says my protocol is 0 and that i need 201 to play.

**Comment by SupremeMortal** [comment]
Probably because you did account for the gap in batched packets.

**Comment by lukeeey** [comment]
idk how to do that lol

**Comment by SupremeMortal** [comment]
I've updated my fork to 1.2.5. You should probably take a look at it. https://github.com/SupremeMortal/voxelwind
